/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBotTickRouteImport } from './routes/api/public/bot-tick'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthApiAuthSplatRouteImport } from './routes/auth/api/auth/$'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotTickRoute = ApiPublicBotTickRouteImport.update({
  id: '/api/public/bot-tick',
  path: '/api/public/bot-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthApiAuthSplatRoute = AuthApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/bot-tick': typeof ApiPublicBotTickRoute
  '/auth/api/auth/$': typeof AuthApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/bot-tick': typeof ApiPublicBotTickRoute
  '/auth/api/auth/$': typeof AuthApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/bot-tick': typeof ApiPublicBotTickRoute
  '/auth/api/auth/$': typeof AuthApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/api/public/bot-tick'
    | '/auth/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/api/public/bot-tick'
    | '/auth/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/api/public/bot-tick'
    | '/auth/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicBotTickRoute: typeof ApiPublicBotTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot-tick': {
      id: '/api/public/bot-tick'
      path: '/api/public/bot-tick'
      fullPath: '/api/public/bot-tick'
      preLoaderRoute: typeof ApiPublicBotTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/api/auth/$': {
      id: '/auth/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/auth/api/auth/$'
      preLoaderRoute: typeof AuthApiAuthSplatRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthApiAuthSplatRoute: typeof AuthApiAuthSplatRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthApiAuthSplatRoute: AuthApiAuthSplatRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicBotTickRoute: ApiPublicBotTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
